In [15]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [16]:
data = pd.read_csv("/content/loans_full_schema.csv")

In [17]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 55 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   emp_title                         9167 non-null   object
 1   emp_length                        9183 non-null   float64
 2   state                             10000 non-null  object
 3   homeownership                     10000 non-null  object
 4   annual_income                     10000 non-null  float64
 5   verified_income                   10000 non-null  object
 6   debt_to_income                    9976 non-null   float64
 7   annual_income_joint               1495 non-null   float64
 8   verification_income_joint         1455 non-null   object
 9   debt_to_income_joint              1495 non-null   float64
 10  delinq_2y                         10000 non-null  int64
 11  months_since_last_delinq          4342 non-null   float64
 12  earliest_credit_line              10000 non-null  int64
 13  inquiries_last_12m                10000 non-null  int64
 14  total_credit_lines                10000 non-null  int64
 15  open_credit_lines                 10000 non-null  int64
 16  total_credit_limit                10000 non-null  int64
 17  total_credit_utilized             10000 non-null  int64
 18  num_collections_last_12m          10000 non-null  int64
 19  num_historical_failed_to_pay      10000 non-null  int64
 20  months_since_90d_late             2285 non-null   float64
 21  current_accounts_delinq           10000 non-null  int64
 22  total_collection_amount_ever      10000 non-null  int64
 23  current_installment_accounts      10000 non-null  int64
 24  accounts_opened_24m               10000 non-null  int64
 25  months_since_last_credit_inquiry  8729 non-null   float64
 26  num_satisfactory_accounts         10000 non-null  int64
 27  num_accounts_120d_past_due        9682 non-null   float64
 28  num_accounts_30d_past_due         10000 non-null  int64
 29  num_active_debit_accounts         10000 non-null  int64
 30  total_debit_limit                 10000 non-null  int64
 31  num_total_cc_accounts             10000 non-null  int64
 32  num_open_cc_accounts              10000 non-null  int64
 33  num_cc_carrying_balance           10000 non-null  int64
 34  num_mort_accounts                 10000 non-null  int64
 35  account_never_delinq_percent      10000 non-null  float64
 36  tax_liens                         10000 non-null  int64
 37  public_record_bankrupt            10000 non-null  int64
 38  loan_purpose                      10000 non-null  object
 39  application_type                  10000 non-null  object
 40  loan_amount                       10000 non-null  int64
 41  term                              10000 non-null  int64
 42  interest_rate                     10000 non-null  float64
 43  installment                       10000 non-null  float64
 44  grade                             10000 non-null  object
 45  sub_grade                         10000 non-null  object
 46  issue_month                       10000 non-null  object
 47  loan_status                       10000 non-null  object
 48  initial_listing_status            10000 non-null  object
 49  disbursement_method               10000 non-null  object
 50  balance                           10000 non-null  float64
 51  paid_total                        10000 non-null  float64
 52  paid_principal                    10000 non-null  float64
 53  paid_interest                     10000 non-null  float64
 54  paid_late_fees                    10000 non-null  float64
dtypes: float64(17), int64(25), object(13)
memory usage: 4.2+ MB

In [18]:
data.head()

,emp_title,emp_length,state,homeownership,annual_income,verified_income,debt_to_income,annual_income_joint,verification_income_joint,debt_to_income_joint,...,sub_grade,issue_month,loan_status,initial_listing_status,disbursement_method,balance,paid_total,paid_principal,paid_interest,paid_late_fees
0,global config engineer,3.0,NJ,MORTGAGE,90000.0,Verified,18.01,NaN,NaN,NaN,...,C3,Mar-2018,Current,whole,Cash,27015.86,1999.33,984.14,1015.19,0.0
1,warehouse office clerk,10.0,HI,RENT,40000.0,Not Verified,5.04,NaN,NaN,NaN,...,C1,Feb-2018,Current,whole,Cash,4651.37,499.12,348.63,150.49,0.0
2,assembly,3.0,WI,RENT,40000.0,Source Verified,21.15,NaN,NaN,NaN,...,D1,Feb-2018,Current,fractional,Cash,1824.63,281.80,175.37,106.43,0.0
3,customer service,1.0,PA,RENT,30000.0,Not Verified,10.16,NaN,NaN,NaN,...,A3,Jan-2018,Current,whole,Cash,18853.26,3312.89,2746.74,566.15,0.0
4,security supervisor,10.0,CA,RENT,35000.0,Verified,57.96,57000.0,Verified,37.66,...,C3,Mar-2018,Current,whole,Cash,21430.15,2324.65,1569.85,754.80,0.0

In [22]:
data.describe()

,emp_length,annual_income,debt_to_income,annual_income_joint,debt_to_income_joint,delinq_2y,months_since_last_delinq,earliest_credit_line,inquiries_last_12m,total_credit_lines,...,public_record_bankrupt,loan_amount,term,interest_rate,installment,balance,paid_total,paid_principal,paid_interest,paid_late_fees
count,9183.000000,1.000000e+04,9976.000000,1.495000e+03,1495.000000,10000.00000,4342.000000,10000.00000,10000.00000,10000.000000,...,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,5.930306,7.922215e+04,19.308192,1.279146e+05,19.979304,0.21600,36.760709,2001.29000,1.95820,22.679600,...,0.123800,16361.922500,43.272000,12.427524,476.205323,14458.916610,2494.234773,1894.448466,599.666781,0.119516
std,3.703734,6.473429e+04,15.004851,7.016838e+04,8.054781,0.68366,21.634939,7.79551,2.38013,11.885439,...,0.337172,10301.956759,11.029877,5.001105,294.851627,9964.561865,3958.230365,3884.407175,517.328062,1.813468
min,0.000000,0.000000e+00,0.000000,1.920000e+04,0.320000,0.00000,1.000000,1963.00000,0.00000,2.000000,...,0.000000,1000.000000,36.000000,5.310000,30.750000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2.000000,4.500000e+04,11.057500,8.683350e+04,14.160000,0.00000,19.000000,1997.00000,0.00000,14.000000,...,0.000000,8000.000000,36.000000,9.430000,256.040000,6679.065000,928.700000,587.100000,221.757500,0.000000
50%,6.000000,6.500000e+04,17.570000,1.130000e+05,19.720000,0.00000,34.000000,2003.00000,1.00000,21.000000,...,0.000000,14500.000000,36.000000,11.980000,398.420000,12379.495000,1563.300000,984.990000,446.140000,0.000000
75%,10.000000,9.500000e+04,25.002500,1.515455e+05,25.500000,0.00000,53.000000,2006.00000,3.00000,29.000000,...,0.000000,24000.000000,60.000000,15.050000,644.690000,20690.182500,2616.005000,1694.555000,825.420000,0.000000
max,10.000000,2.300000e+06,469.090000,1.100000e+06,39.980000,13.00000,118.000000,2015.00000,29.00000,87.000000,...,3.000000,40000.000000,60.000000,30.940000,1566.590000,40000.000000,41630.443684,40000.000000,4216.440000,52.980000

In [26]:
y = data['verified_income']
X = data[['paid_total']]

In [27]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [28]:
# Обучение модели на реальных данных
model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

In [29]:
# Предсказание на тестовых данных для реальных данных
y_pred = model.predict(X_test)

In [30]:
# Оценка точности на реальных данных
accuracy = accuracy_score(y_test, y_pred)
print("Оценка точности:", accuracy)

Оценка точности: 0.4245

In [31]:
# Генерация новых данных
def generate_data(n_samples):
    generated_data = pd.DataFrame(columns=data.columns)
    for col in data.columns:
        if col in ['paid_total']:
            # Генерация случайных значений в соответствии с распределением исходных данных
            mean = data[col].mean()
            std = data[col].std()
            generated_col = np.random.normal(loc=mean, scale=std, size=n_samples)
        else:
            # Генерация случайных значений для категориальных переменных
            unique_values = data[col].unique()
            generated_col = np.random.choice(unique_values, size=n_samples)
        generated_data[col] = generated_col
    return generated_data

In [32]:
# Генерация 1000000 наборов данных
generated_data = generate_data(1000000)

In [33]:
generated_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 55 columns):
 #   Column                            Non-Null Count    Dtype
---  ------                            --------------    -----
 0   emp_title                         999796 non-null   object
 1   emp_length                        916411 non-null   float64
 2   state                             1000000 non-null  object
 3   homeownership                     1000000 non-null  object
 4   annual_income                     1000000 non-null  float64
 5   verified_income                   1000000 non-null  object
 6   debt_to_income                    999701 non-null   float64
 7   annual_income_joint               998279 non-null   float64
 8   verification_income_joint         750722 non-null   object
 9   debt_to_income_joint              999191 non-null   float64
 10  delinq_2y                         1000000 non-null  int64
 11  months_since_last_delinq          989635 non-null   float64
 12  earliest_credit_line              1000000 non-null  int64
 13  inquiries_last_12m                1000000 non-null  int64
 14  total_credit_lines                1000000 non-null  int64
 15  open_credit_lines                 1000000 non-null  int64
 16  total_credit_limit                1000000 non-null  int64
 17  total_credit_utilized             1000000 non-null  int64
 18  num_collections_last_12m          1000000 non-null  int64
 19  num_historical_failed_to_pay      1000000 non-null  int64
 20  months_since_90d_late             990625 non-null   float64
 21  current_accounts_delinq           1000000 non-null  int64
 22  total_collection_amount_ever      1000000 non-null  int64
 23  current_installment_accounts      1000000 non-null  int64
 24  accounts_opened_24m               1000000 non-null  int64
 25  months_since_last_credit_inquiry  961670 non-null   float64
 26  num_satisfactory_accounts         1000000 non-null  int64
 27  num_accounts_120d_past_due        499895 non-null   float64
 28  num_accounts_30d_past_due         1000000 non-null  int64
 29  num_active_debit_accounts         1000000 non-null  int64
 30  total_debit_limit                 1000000 non-null  int64
 31  num_total_cc_accounts             1000000 non-null  int64
 32  num_open_cc_accounts              1000000 non-null  int64
 33  num_cc_carrying_balance           1000000 non-null  int64
 34  num_mort_accounts                 1000000 non-null  int64
 35  account_never_delinq_percent      1000000 non-null  float64
 36  tax_liens                         1000000 non-null  int64
 37  public_record_bankrupt            1000000 non-null  int64
 38  loan_purpose                      1000000 non-null  object
 39  application_type                  1000000 non-null  object
 40  loan_amount                       1000000 non-null  int64
 41  term                              1000000 non-null  int64
 42  interest_rate                     1000000 non-null  float64
 43  installment                       1000000 non-null  float64
 44  grade                             1000000 non-null  object
 45  sub_grade                         1000000 non-null  object
 46  issue_month                       1000000 non-null  object
 47  loan_status                       1000000 non-null  object
 48  initial_listing_status            1000000 non-null  object
 49  disbursement_method               1000000 non-null  object
 50  balance                           1000000 non-null  float64
 51  paid_total                        1000000 non-null  float64
 52  paid_principal                    1000000 non-null  float64
 53  paid_interest                     1000000 non-null  float64
 54  paid_late_fees                    1000000 non-null  float64
dtypes: float64(17), int64(25), object(13)
memory usage: 419.6+ MB

In [34]:
# Вывод сгенерированных данных для проверки
generated_data.head()

,emp_title,emp_length,state,homeownership,annual_income,verified_income,debt_to_income,annual_income_joint,verification_income_joint,debt_to_income_joint,...,sub_grade,issue_month,loan_status,initial_listing_status,disbursement_method,balance,paid_total,paid_principal,paid_interest,paid_late_fees
0,special enforcement investigator,0.0,KY,RENT,33477.0,Not Verified,18.51,118000.0,Not Verified,12.34,...,B3,Mar-2018,Charged Off,whole,DirectPay,23123.55,-1839.586201,1145.79,2136.28,32.70
1,sales merchandiser,1.0,OH,MORTGAGE,52500.0,Verified,27.54,75765.0,NaN,33.53,...,E4,Mar-2018,Current,whole,Cash,15509.52,2595.873372,613.91,758.83,21.10
2,salon leader,3.0,ND,MORTGAGE,161000.0,Source Verified,31.67,143000.0,NaN,30.13,...,C4,Feb-2018,Current,whole,DirectPay,6902.60,2277.192827,609.03,217.79,15.00
3,team leader,NaN,IN,MORTGAGE,22568.0,Not Verified,6.11,166000.0,Not Verified,24.07,...,D3,Mar-2018,Charged Off,fractional,DirectPay,9528.72,8262.035452,800.00,199.52,30.33
4,crisis counselor,1.0,KS,RENT,132323.0,Verified,3.66,83600.0,Verified,26.53,...,E1,Jan-2018,In Grace Period,fractional,DirectPay,22935.96,5130.140660,599.41,569.80,36.67

In [35]:
# Подготовка данных
y_generated = generated_data['verified_income']
X_generated = generated_data[['paid_total']]

In [36]:
# Разделение данных на обучающую и тестовую выборки
X_train_generated, X_test_generated, y_train_generated, y_test_generated = train_test_split(X_generated, y_generated, test_size=0.2, random_state=42)

In [37]:
# Обучение модели на сгенерированных данных
model_generated = LogisticRegression()
model_generated.fit(X_train_generated, y_train_generated)

LogisticRegression()

In [38]:
# Предсказание на тестовых данных для сгенерированных данных
y_pred_generated = model_generated.predict(X_test_generated)

In [39]:
# Оценка точности на сгенерированных данных
accuracy_generated = accuracy_score(y_test_generated, y_pred_generated)
print("Оценка точности:", accuracy_generated)

Оценка точности: 0.33375